// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrmXrN0hLve3FgMn8eCJv7iJKuK1IQBHE',
    appId: '1:309769085223:web:d921e9bd8d49db8a0a4902',
    messagingSenderId: '309769085223',
    projectId: 'feminova',
    authDomain: 'feminova.firebaseapp.com',
    storageBucket: 'feminova.appspot.com',
    measurementId: 'G-53BHLV9TBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqj12IB9YWDQDmyMLmN15fqBiVbpN6ts',
    appId: '1:309769085223:android:3377e10f0ca0a5510a4902',
    messagingSenderId: '309769085223',
    projectId: 'feminova',
    storageBucket: 'feminova.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmsPT8HPGmy8Ins0MeBT2fH_cWzu0x0M',
    appId: '1:309769085223:ios:f0fe2d08391c68ca0a4902',
    messagingSenderId: '309769085223',
    projectId: 'feminova',
    storageBucket: 'feminova.appspot.com',
    iosClientId: '309769085223-jbas4u922abfe118ddgitlt80b2ll5c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.feminova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdmsPT8HPGmy8Ins0MeBT2fH_cWzu0x0M',
    appId: '1:309769085223:ios:f0fe2d08391c68ca0a4902',
    messagingSenderId: '309769085223',
    projectId: 'feminova',
    storageBucket: 'feminova.appspot.com',
    iosClientId: '309769085223-jbas4u922abfe118ddgitlt80b2ll5c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.feminova',
  );
}
